import { Corps, DCIEvent, Market, Outcome } from "@/types/dci";

export const corps: Corps[] = [
  {
    id: "bluecoats",
    name: "Bluecoats",
    division: "World Class",
  },
  {
    id: "carolina-crown",
    name: "Carolina Crown",
    division: "World Class",
  },
  {
    id: "blue-devils",
    name: "Blue Devils",
    division: "World Class",
  },
  {
    id: "santa-clara-vanguard",
    name: "Santa Clara Vanguard",
    division: "World Class",
  },
  {
    id: "boston-crusaders",
    name: "Boston Crusaders",
    division: "World Class",
  },
  {
    id: "phantom-regiment",
    name: "Phantom Regiment",
    division: "World Class",
  },
  {
    id: "cadets",
    name: "The Cadets",
    division: "World Class",
  },
  {
    id: "cavaliers",
    name: "The Cavaliers",
    division: "World Class",
  },
  {
    id: "madison-scouts",
    name: "Madison Scouts",
    division: "World Class",
  },
  {
    id: "crossmen",
    name: "Crossmen",
    division: "World Class",
  },
];

export const dciEvents: DCIEvent[] = [
  {
    id: "dci-finals-2024",
    name: "DCI World Championship Finals",
    date: "2024-08-10",
    location: "Indianapolis, IN",
    status: "upcoming",
    type: "finals",
  },
  {
    id: "dci-semifinals-2024",
    name: "DCI World Championship Semifinals",
    date: "2024-08-09",
    location: "Indianapolis, IN",
    status: "upcoming",
    type: "championship",
  },
  {
    id: "dci-eastern-classic-2024",
    name: "DCI Eastern Classic",
    date: "2024-07-27",
    location: "Allentown, PA",
    status: "upcoming",
    type: "regional",
  },
  {
    id: "dci-southwest-championship-2024",
    name: "DCI Southwest Championship",
    date: "2024-07-20",
    location: "San Antonio, TX",
    status: "upcoming",
    type: "regional",
  },
];

export const markets: Market[] = [
  {
    id: "dci-finals-2024-winner",
    eventId: "dci-finals-2024",
    title: "DCI Finals 2024 Winner",
    description: "Which corps will win the 2024 DCI World Championship?",
    type: "placement",
    status: "active",
    outcomes: [
      {
        id: "bluecoats-1st",
        marketId: "dci-finals-2024-winner",
        title: "Bluecoats",
        description: "Bluecoats to win DCI Finals 2024",
        odds: 3.2,
        totalBets: 156,
        totalVolume: 12500,
        corpsId: "bluecoats",
        position: 1,
      },
      {
        id: "carolina-crown-1st",
        marketId: "dci-finals-2024-winner",
        title: "Carolina Crown",
        description: "Carolina Crown to win DCI Finals 2024",
        odds: 2.8,
        totalBets: 203,
        totalVolume: 18750,
        corpsId: "carolina-crown",
        position: 1,
      },
      {
        id: "blue-devils-1st",
        marketId: "dci-finals-2024-winner",
        title: "Blue Devils",
        description: "Blue Devils to win DCI Finals 2024",
        odds: 4.1,
        totalBets: 98,
        totalVolume: 8900,
        corpsId: "blue-devils",
        position: 1,
      },
      {
        id: "santa-clara-vanguard-1st",
        marketId: "dci-finals-2024-winner",
        title: "Santa Clara Vanguard",
        description: "Santa Clara Vanguard to win DCI Finals 2024",
        odds: 5.5,
        totalBets: 67,
        totalVolume: 5200,
        corpsId: "santa-clara-vanguard",
        position: 1,
      },
    ],
  },
  {
    id: "dci-finals-2024-top-3",
    eventId: "dci-finals-2024",
    title: "DCI Finals 2024 Top 3",
    description: "Which corps will finish in the top 3 at DCI Finals 2024?",
    type: "placement",
    status: "active",
    outcomes: [
      {
        id: "bluecoats-top-3",
        marketId: "dci-finals-2024-top-3",
        title: "Bluecoats Top 3",
        description: "Bluecoats to finish in top 3",
        odds: 1.4,
        totalBets: 312,
        totalVolume: 25600,
        corpsId: "bluecoats",
        position: 3,
      },
      {
        id: "carolina-crown-top-3",
        marketId: "dci-finals-2024-top-3",
        title: "Carolina Crown Top 3",
        description: "Carolina Crown to finish in top 3",
        odds: 1.3,
        totalBets: 398,
        totalVolume: 31200,
        corpsId: "carolina-crown",
        position: 3,
      },
      {
        id: "phantom-regiment-top-3",
        marketId: "dci-finals-2024-top-3",
        title: "Phantom Regiment Top 3",
        description: "Phantom Regiment to finish in top 3",
        odds: 2.1,
        totalBets: 189,
        totalVolume: 15800,
        corpsId: "phantom-regiment",
        position: 3,
      },
    ],
  },
  {
    id: "dci-eastern-classic-2024-winner",
    eventId: "dci-eastern-classic-2024",
    title: "DCI Eastern Classic 2024 Winner",
    description: "Which corps will win the 2024 DCI Eastern Classic?",
    type: "placement",
    status: "active",
    outcomes: [
      {
        id: "boston-crusaders-eastern-1st",
        marketId: "dci-eastern-classic-2024-winner",
        title: "Boston Crusaders",
        description: "Boston Crusaders to win Eastern Classic 2024",
        odds: 2.5,
        totalBets: 87,
        totalVolume: 6700,
        corpsId: "boston-crusaders",
        position: 1,
      },
      {
        id: "cadets-eastern-1st",
        marketId: "dci-eastern-classic-2024-winner",
        title: "The Cadets",
        description: "The Cadets to win Eastern Classic 2024",
        odds: 3.1,
        totalBets: 64,
        totalVolume: 4800,
        corpsId: "cadets",
        position: 1,
      },
      {
        id: "cavaliers-eastern-1st",
        marketId: "dci-eastern-classic-2024-winner",
        title: "The Cavaliers",
        description: "The Cavaliers to win Eastern Classic 2024",
        odds: 4.2,
        totalBets: 43,
        totalVolume: 3200,
        corpsId: "cavaliers",
        position: 1,
      },
    ],
  },
];